apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bot-factory.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bot-factory.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bot-factory.name" . }}
    spec:
      containers:
        - name: bot-factory
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
