replicaCount: 1

image:
  repository: your-dockerhub-username/bot-factory
  tag: v5.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

resources: {}